- dump/dump_manager.cpp
Review link: https://gerrit.openbmc-project.xyz/c/openbmc/openpower-debug-collector/+/47061
When the dumps are disabled the dump entry will not get created
and the xyz.openbmc_project.Dump.Create.Error.Disabled error
will be thrown. Catch this and return the same error for the caller
to handle.
Test:
root@rain148bmc:~# busctl --verbose call org.open_power.Dump.Manager /org/openpower/dump xyz.openbmc_project.Dump.Create CreateDump a{sv} 2 "com.ibm.Dump.Create.CreateParameters.DumpType" s "com.ibm.Dump.Create.DumpType.Hostboot" "com.ibm.Dump.Create.CreateParameters.ErrorLogId"  t 0xDEADBEEF
Call failed: Dump is disabled on this system.
Change-Id: I06cde78143226ed26191d798d012015bdef54e2a
> Handle dump disabled exception

- README.md
- dump/dump_collect.cpp
- dump/dump_collect.hpp
- dump/dump_manager.cpp
- dump/dump_manager.hpp
- dump/dump_manager_main.cpp
- dump/dump_utils.cpp
- dump/dump_utils.hpp
- dump/meson.build
- dump/org.open_power.Dump.Manager.service
- dump/sbe_consts.hpp
- meson.build
- meson_options.txt
- sbe_consts.hpp
Review link: https://gerrit.openbmc-project.xyz/c/openbmc/openpower-debug-collector/+/47038
SBE is a microcontroller that sits inside the processor
to initialize it to start the booting and also acts as a secure channel
for accessing certain control functions on the processor. During the
booting or other hardware access operations SBE can encounter errors
and become unresponsive. In such situations, the debug data needs to be
collected from such SBEs to find out the root cause of the error.
This data includes hardware state, configuration, memory, etc.
The collected data is then packaged into the OpenPOWER dump format
and which is called as SBE dump.
The SBE dump is collected from an responsive SBE using special procedures
which execute hardware access instructions to get the memory
and …
> Add support for collecting Self Boot Engine(SBE) dump

- dump/dump_manager.cpp
Need to handle additional errors returned during dump
create and return to the caller.
QuotaExceeded: No more space left for the dump.
NotAllowed: Dump is not allowed at this time.
Tests: force returned both errors from
phosphor-debug-collector to test this path
Change-Id: Ie7b060085d4faf44367166999274864fc1e923b8
Conflicts:
dump/dump_manager.cpp
Gerrit link https://gerrit.openbmc-project.xyz/c/openbmc/openpower-debug-collector/+/50292
> Handle dump create errors

- watchdog/ffdc_file.cpp
- watchdog/ffdc_file.hpp
- watchdog/file_descriptor.hpp
- watchdog/meson.build
- watchdog/utils.cpp
- watchdog/utils.hpp
- watchdog/watchdog_dbus.cpp
- watchdog/watchdog_dbus.hpp
- watchdog/watchdog_logging.cpp
- watchdog/watchdog_main.cpp
- watchdog/watchdog_main.hpp
This commit provides additional callout support for SBE when the
host does not respond within watchdog timeout interval during SBE
boot window.
Testing:
Steps used:
1. obmcutil poweroff
2. istep -s0
3. systemctl start org.open_power.Dump.Manager.service
4. systemctl start openpower-debug-collector-watchdog@0.service
5. Check the journal log, and get the PEL id to print PEL info
PEL info:
"Callout Section": {
"Callout Count":        "2",
"Callouts": [{
"FRU Type":         "Maintenance Procedure Required",
"Priority":         "Mandatory, replace all with this type
as a unit",
"Procedure":        "BMC0002"
}, {
"FRU Type":         "Normal Hardware FRU",
"Priority":         "Medium Priority",
"Location Code":    "xxxxxxxxxxxxx",
"Part Number":      "xxxxx",
"CCIN":             "xxxx",
"Serial …
> Callout support for SBE when watchdog times out

- watchdog/watchdog_dbus.cpp
- watchdog/watchdog_dbus.hpp
- watchdog_timeout.cpp
When CurrentHostStatus is not in 'Running' state, either host is 'Off'
or current state is changed by HW dump to a state other than 'Running'
and may have initiated/created the dump. In these cases, there is
no need to initiate hostboot dump. This commit allows initiating
hostboot dump collection when the current host state is 'Running'
and the watchdog times out.
Testing:
Run watchdog_timeout and check the following entries in the journal log:
'Running' state:
Mar 03 12:22:34 rain127bmc watchdog_timeout[3626]: Host did not respond
within watchdog timeout interval
Mar 03 12:22:34 rain127bmc watchdog_timeout[3626]: Handle Hostboot boot
failure
Mar 03 12:22:34 rain127bmc watchdog_timeout[3626]: hostboot dump
requested
Mar 03 12:23:26 rain127bmc watchdog_timeout[3626]: …
> Request hostboot dump when Host State is 'Running'

- dump/org.open_power.Dump.Manager.service
Add service org.open_power.Dump.Manager to control the
openpower-dump-manager application for collecting the
openpower dumps on BMC.
Patch to link service file:
https://gerrit.openbmc-project.xyz/c/openbmc/openbmc/+/42327
Change-Id: I7adf5848eec674d7997ba24e56a5a1265cd8c3eb
> openpower-dump-manager needs to be up when chassis on

- dump/dump_manager.cpp
- dump/dump_manager.hpp
- dump/dump_manager_main.cpp
The event mechanism was supporting only one dump at a time
because the second dump was requested was overwriting the
first one. Changed event mechanism as in phosphor-debug-
collector
Tested
Created 4 SBE dumps together and offloaded
Change-Id: I4ecee76041a3161094d0161ebdbb711ef15a2090
> Fix crash while requesting multiple SBE dumps

- dump/dump_manager.cpp
- dump/dump_utils.cpp
- dump/dump_utils.hpp
An additional BMC dump will help debugging the host error
because the journal and the error log on the BMC can help
debugging the host errors. Add a new method to request
BMC dump at the end of the collection
Tests:
Intitiate SBE, Hostboot and Hardware dumps and make sure
BMC dumps are created and not impacted the collection
host dumps
Change-Id: Id29d3044306f23842242b62697c7cdc397481ec7
> Request a BMC dump at the end of system dump collection

- watchdog/watchdog_main.cpp
Curently all the SBE timeout use case default callout is included
In the PEL. This commit is used to add the callout for SBE timeout
Without SBE FFDC use case.  If SBE provides FFDC during watchdog
Timeout case , BMC need to honour the callout provided by SBE.
Upstream Review https://gerrit.openbmc-project.xyz/c/openbmc/openpower-debug-collector/+/53029
> SBE  watchdog times out callout support enhancement

- dump/dump_manager.cpp
- dump/dump_manager.hpp
For every dump generated an "anon_inode:[pidfd]" entry is created for the
associated process and the same is not released. When the number of inode
entries reach the maximum count dump request will fail and the dump service
takes a reset with a core dump.
When a dump is requested a child process is spawned to perform dump collection.
Parent process waits on the child process completion using sd-event-add-child
systemd call. sd-event-add-child adds an inode entry which needs to be released
during the callback method called after child process exit using unref but the
same is not done.
Now switching to sdeventplus::source::Child wrapper class for sd-event-add-child
which takes care of releasing the inode fd.
Tested:
tested hardware, sbe , resource dump generation successfully
Signed-off-by: …
> sdevent - cater for releasing linux inode for openpower dumps

- dump/dump_manager.hpp
Looks like the "true" was just a copy/paste from elsewhere. Remove it
(since no longer supported) and utilize the default which is to emit an
object added signal on constructor call.
Signed-off-by: Andrew Geissler <geissonator@yahoo.com>
> sdbusplus: object: don't use 'bool' argument constructor

- dump/dist/meson.build
- dump/dist/org.open_power.Dump.Manager@.service.in
- dump/meson.build
Made changes to install the org.open_power.Dump.Manager@.service as part of the repository build and also create soft links.
1) Now modified to install the service file and create softlink as part of repository build
2) Modified the service file with templated approach as the service starts before start host@i target.
Upstream commit link
https://gerrit.openbmc.org/c/openbmc/openpower-debug-collector/+/42328
Tested
root@p10bmc:~# obmcutil state
CurrentBMCState     : xyz.openbmc_project.State.BMC.BMCState.Ready
CurrentPowerState   : xyz.openbmc_project.State.Chassis.PowerState.On
CurrentHostState    : xyz.openbmc_project.State.Host.HostState.Off
BootProgress        : xyz.openbmc_project.State.Boot.Progress.ProgressStages.Unspecified
OperatingSystemState: …
> dump : fix service file and install as part of repository build

- dump/dist/meson.build
- dump/dist/org.open_power.Dump.Manager.service.in
upstream commit link
https://gerrit.openbmc.org/c/openbmc/openpower-debug-collector/+/42328
Tested:
root@p10bmc:~# systemctl status org.open_power.Dump.Manager.service
* org.open_power.Dump.Manager.service - OpenPOWER Dump Manager Host Loaded: loaded (/lib/systemd/system/org.open_power.Dump.Manager.service; enabled; preset: enabled)
Active: active (running) since Thu 2023-02-23 07:38:42 UTC; 26s ago
Main PID: 997 (openpower-dump-)
CGroup: /system.slice/org.open_power.Dump.Manager.service
`-997 /usr/bin/openpower-dump-manager
Feb 23 07:38:42 p10bmc systemd[1]: Starting OpenPOWER Dump Manager Host...
Feb 23 07:38:42 p10bmc systemd[1]: Started OpenPOWER Dump Manager Host.
Change-Id: I13e4b18ce23746b882598a5f0d93faa108b4761f
> dump: change dump service to non template version

- dump/dist/meson.build
- meson.build
- watchdog/watchdog_logging.cpp
- watchdog_timeout.cpp
Update host watch dog timeout event name to match in both hostboot-dump-collection enabled and disabled state.
Move the configuration file generation outside the executable block
Upstream links:
https://gerrit.openbmc.org/c/openbmc/openpower-debug-collector/+/62812
https://gerrit.openbmc.org/c/openbmc/openpower-debug-collector/+/62813
Test:
Tested and creates the expected PEL.
> Update Host Watchdog timeout event name

- dump/dist/org.open_power.Dump.Manager.service.in
Upstream yocto introduced a change via e510222 (systemd-systemctl: fix instance template WantedBy symlink construction).
This fixes a bug that we in OpenBMC had been taking advantage of in that we were able to document our templated target dependencies without it actually doing anything. The real installation of services within targets occurs in our bitbake recipes due to the complexity of chassis and host instances on a per machine basis.
Leave the dependency information in the service files but comment them out. It's useful to be able to look at a service and understand which targets it's going to be installed into by the bitbake recipes.
The meson file within this repo installs the service so there is no other changes needed here.
> systemd: no installation in templated targets

- watchdog/watchdog_main.cpp
- watchdog/watchdog_main.hpp
- watchdog_timeout.cpp
Using the xyz.openbmc_project.State.Host interface to determine the operational status of the host becomes less precise when shifting from hostboot to host. In the interim phase when host is initializing and hasn't reached full functionality, the host's state is inaccurately assumed to be in hostboot. In cases where host encounters initial boot challenges and the watchdog timer triggers because the boot process hasn't finished within the set time, this watchdog misinterprets the situation as a hostboot problem.
To address this, there exists a core scratch register that undergoes an update by hostboot just before transferring control to host. We have devised a method that leverages this register to determine whether the transition to host has already occurred.
By implementing this …
> watchdog:Trigger System Dump when host load fails

- meson.build
- watchdog/watchdog_main.cpp
Our 1050-ghe level only has yocto 1.0.0 and c++20 so be sure to support that in this projects 1050 branch.
> 1050: support meson level in yocto 1050-ghe

- watchdog/watchdog_main.cpp
- watchdog/watchdog_main.hpp
- watchdog_timeout.cpp
```
Using the xyz.openbmc_project.State.Host interface to determine the
operational status of the host becomes less precise when shifting from
hostboot to host. In the interim phase when host is initializing and
hasn't reached full functionality, the host's state is inaccurately
assumed to be in hostboot. In cases where host encounters initial boot
challenges and the watchdog timer triggers because the boot process
hasn't finished within the set time, this watchdog misinterprets the
situation as a hostboot problem.
To address this, there exists a core scratch register that undergoes an
update by hostboot just before transferring control to host. We have
devised a method that leverages this register to determine whether the
transition to host has already occurred.
By implementing this …
```
> 1060: watchdog:Trigger System Dump when host load fails

- watchdog/watchdog_main.cpp
Use the fmt::format library call that is supported
Change-Id: I4fee2129f1d07ec1eda6555be91e8214f2822e5c
Signed-off-by: Parasa Swetha <parasa.swetha1@ibm.com>
> Fix CI Failure

- dump/dump_collect.cpp
- dump/dump_collect.hpp
This commit introduces the functionality to support hardware dump
collection in Odyssey systems. The implementation includes
necessary modifications to the dump manager to handle Odessey
specific changes to collect dumps from SBE.
Tests:
busctl --verbose call org.open_power.Dump.Manager /org/openpower/dump xyz.openbmc_project.Dump.Create CreateDump a{sv} 3  "com.ibm.Dump.Create.CreateParameters.DumpType" s "com.ibm.Dump.Create.DumpType.Hardware" "com.ibm.Dump.Create.CreateParameters.ErrorLogId" t 0xDEADBEEF "com.ibm.Dump.Create.CreateParameters.FailingUnitId" t 1
MESSAGE "o" {
OBJECT_PATH "/xyz/openbmc_project/dump/hardware/entry/14";
};
ec 13 05:58:38 ever6bmc dump-collect[7758]: Dump collection completed for clock_state(2)
Dec 13 05:58:41 ever6bmc phosphor-dump-manager[8001]: …
> Support for HW dump from Odyssey

- dump/dump_collect.cpp
Use the newly added api in pdbg to check if the pdbg target is of ocmb and is of ddr5 ody.
Change-Id: I8209743f143c9d99fda509045e814839fbb7817a
> dump: use pdbg method to check target is of ody ocmb

- dump/dump_collect.cpp
- dump/dump_utils.cpp
- dump/dump_utils.hpp
- Need to collect fast arrays from all OCMB chips during HW dump collection
- Initiate OCMB SBE dump in the case of a chipop timeout
> Fix for fast array collection

- dump/create_pel.cpp
- dump/sbe_dump_collector.cpp
Hardware failure dumps or boot failure dumps are collected when the systems are in a critically bad state. Additional errors that occur during the dump collection may be side effects of the prior failures. Thus, logging all such errors as informational helps avoid unwanted alerts.
Tests:
WIthout change
"0x50002C17": {
"SRC":                  "BD123500",
"Message":              "chipop request failure reported by SBE",
"PLID":                 "0x50002C17",
"CreatorID":            "BMC",
"Subsystem":            "Processor Chip Cache",
"Commit Time":          "05/03/2024 15:27:09",
"Sev":                  "Unrecoverable Error",
"CompID":               "bmc common host processor errors"
},
With change
root@ever6bmc:/tmp# peltool --info -l -h
{
"0x50002C27": {
"SRC": …
> Log all PELs as informational

- .shellcheck-ignore
- dump/dist/meson.build
- dump/dist/openpower-dump-monitor.service
- dump/dump_monitor.cpp
- dump/dump_monitor.hpp
- dump/dump_monitor_main.cpp
- dump/meson.build
- dump/sbe_dump_collector.cpp
- dump/tools/common/include/gendumpheader
- dump/tools/common/include/gendumpinfo
- dump/tools/common/include/meson.build
- dump/tools/common/meson.build
- dump/tools/meson.build
- dump/tools/opdump/meson.build
- dump/tools/opdump/opdreport
- meson.build
71527: Create Dump Header for IBM Systems | https://gerrit.openbmc.org/c/openbmc/openpower-debug-collector/+/71527
71513: Add opdreport tool to OpenPOWER Debug Collector | https://gerrit.openbmc.org/c/openbmc/openpower-debug-collector/+/71513
71514: Add script to generate dump info file | https://gerrit.openbmc.org/c/openbmc/openpower-debug-collector/+/71514
71528: Dump id needs to be hex dump files | https://gerrit.openbmc.org/c/openbmc/openpower-debug-collector/+/71528
71531: Add '0x' Prefix to Indicate Hexadecimal Values | https://gerrit.openbmc.org/c/openbmc/openpower-debug-collector/+/71531
71515: Add Dump Monitoring Support | https://gerrit.openbmc.org/c/openbmc/openpower-debug-collector/+/71515
71640: Add support for system dump | …
> Dump collection support in 1110

- dump/dump_collect.cpp
Log PELs as informational during dumping path since system is already in bad state and any errors while collecting dump can be due to the side effect of original failure.
> Log PEL as informational during dump path

- dump/dist/clear_resourcedumps_poweroff.service
- dump/dist/clear_systemdumps_poweroff.service
- dump/dist/meson.build
- dump/tools/opdump/dumpdelete
- dump/tools/opdump/meson.build
Move the clear_hostdumps_poweroff.service to openpower-debug-collector as it is needed only on IBM systems. Additionally added the scripts to selectively delete all entries based on the dump interface to delete only resource dump and system dump during power off.
Each type of dump will have separate service files due to difference in activation, system dump entries are not cleared during an mpreboot
Change-Id: Ibf20b097862acb3dc7887cd75d4d5ba6bc1ff5c3
> Move clear host dump service to openpower-debug-collector

- dump/tools/bmcdump/scripts/package
- dump/tools/common/include/gendumpheader
- dump/tools/common/include/opfunctions
- dump/tools/opdump/opdreport
There are two parameters available for each dump,
Originator ID and Originator Type. This change
aims to include these fields into the BMC dump
header.
If for any reason either the originator ID or
originator type or both are unavailable then
they are been replaced by their allocated null
bytes.
Test Results:
Tested on generated BMC dumps and verified.
> gendumpheader: Originator details info added

- dump/tools/opdump/opdreport
Test Results:
Before:
```
>>>> Processing dump files
  Processing: SYSDUMP.13E09F0.00000007.20240913135832  
  Dump Type is: UNKNOWN
>>>> Processing dump files
  Processing: SYSDUMP.13ECF8X.20000008.20240916083507
Dump Type is: UNKNOWN  ```
After:
```>>>> Processing dump files
Processing: SYSDUMP.1012345.00000008.20240903113715
Dump Type is: SCS
>>>> Processing dump files
Processing: SYSDUMP.1012345.20000007.20240903113517
Dump Type is: HB```
Change-Id: Ic0a85b2a0dee43629dde920c5f13af05e6fb8347
> opdreport: opdreport: Eliminate undeclared variable; use existing variable instead

- dump/tools/common/include/opfunctions
Dump Id in BMC Dump Filename is padded to 7 digits instead of 8 digits. This is causing file name mismatch between the dump offloaded to HMC/OS and the dump stored on BMC. Fixing this issue by padding Dump Id to 8 digits.
Test Results:
Before:
root@p10bmc:/var/lib/phosphor-debug-collector/dumps/6# ls BMCDUMP.13ECF8X.0000006.20241001051003
After:
root@p10bmc:/var/lib/phosphor-debug-collector/dumps/17# ls BMCDUMP.1012345.00000017.20330125023119
Change-Id: I04c469ad3aaf6480c5732445ba7f8e644357262e
> opfunctions: Fix dumpId length

- dump/tools/common/include/gendumpheader
Issue 1: When both originator_type and originator_id are empty,
only 4 bytes is being null padded(after 1st if check)
instead of the reserved 36 bytes that was intended for
originator details. This is causing missed padding.
Issue 2: Only originator_type could be valid with originator_id empty,
in which case it is not intended to add either of them,
instead padding of 36 null Byte is the expected outcome.
Fix: If either of originator_id or originator_type is empty, pad 36B.
Test Results: Verified that BMC Dumps are generated with padding.
> gendumpheader: Include both originator details or none in dump header

- dump/tools/common/include/gendumpheader
- dump/tools/common/include/opfunctions
Issue1: Originator_Id string is not getting extracted properly.
Fix to extract Originator_id string correctly.
Issue2: Currently if either of the originator id or type is empty
the other is not being included in the dump header.
Add either of them even if one is missing.
Test Results:
BMC Dumps initiated from Web-UI
ORIGINATOR_ID EMPTY  ORIGINATOR_TYPE = '0'
00000220  .......   |YW30UF15700C0...|
00000230  .......   |................|
ORIGINATOR_ID = 1.2.3.4 ORIGINATOR_TYPE is EMPTY
00000220  .......   |YW30UF15700C....|
00000230  .......   |1.2.3.4.........|
ORIGINATOR_ID = 1.2.3.4 ORIGINATOR_TYPE = '0'
00000220  .......   |YW30UF15700C0...|
00000230  .......   |1.2.3.4.........|
BMC Dump initiated using busctl command
00000220  .......   |YW30UF15700C1...|
00000230  ....... …
> gendumpheader: Add originator id & type even if either is missing.

- .shellcheck-ignore
- dump/create_pel.cpp
- dump/create_pel.hpp
- dump/sbe_dump_collector.cpp
- dump/sbe_dump_collector.hpp
- dump/tools/common/include/gendumpheader
Test Results:
root@p10bmc:/tmp/test# cat /tmp/dump_20000005_1737700066/info.yaml ErrorInfo:
PELId: 1342183604
src: BD123501
Resource: proc 1
Change-Id: I920d646e2533a8fa7ae1aed42d63a9e4bac7f771
> Add error information to dump on collection failures

- dump/sbe_dump_collector.cpp
- dump/tools/common/include/gendumpinfo
Recently there was a requirement to add dump collection failures to info.yaml file. This has caused an issue in makedump tool parsing as the ErrorInfo details are added as a separate document. Fixing this by appending ErrorInfo details at the end of info.yaml file.
Change-Id: I74c2fb8ebc31d1c3bd60feffa3f0467faa435d5c
> dump: Fix info.yaml to work with makedump tool

- .shellcheck-ignore
- dump/tools/bmcdump/plugins/hostboot
This change is picked from
https://gerrit.openbmc.org/c/openbmc/phosphor-debug-collector/+/52594
HBEL    (Hostboot error logs)
HBD_RW  (Hostboot preserved attributes)
EECACHE (Hostboot VPD cache)
Tested:
```
Wed Apr 13 08:13:31 UTC 2022 INFO: Copied HBEL /media/hostfw/running/HBEL
Wed Apr 13 08:13:31 UTC 2022 INFO: Copied HBD_RW /media/hostfw/running/HBD_RW
Wed Apr 13 08:13:31 UTC 2022 INFO: Copied EECACHE /media/hostfw/running/EECACHE
root@rain104bmc:/tmp/test/obmcdump_00000000_1649837600# ls -la HBEL
-rw-r-----    1 root     root        147456 Apr 13 08:13 HBEL
root@rain104bmc:/tmp/test/obmcdump_00000000_1649837600# ls -lah HBEL
-rw-r-----    1 root     root      144.0K Apr 13 08:13 HBEL
-rw-r-----    1 root     root        2.0M Apr 13 08:13 HBD_RW …
```
> opdreport: add host preserved partitions to BMC dump

- dump/tools/bmcdump/plugins/occ
Send USR1 signal to openpower-occ-control app to collect it's dump data
to be added to a BMC dump.
Tested on Rainier:
OCCs not running:
```
$ cat BMCDUMP.139F210.00000000.20250801210223_out/archive/occ_control_dump.json
{
"objectCount": "4 OCC objects",
"occ0": {
"occState": "NOT ACTIVE"
},
"occ1": {
"occState": "NOT ACTIVE"
},
"occ2": {
"occState": "NOT ACTIVE"
},
"occ3": {
"occState": "NOT ACTIVE"
}
}
```
OCCs running:
```
$ cat BMCDUMP.139F210.00000000.20250801191023_out/archive/occ_control_dump.json
{
"objectCount": "4 OCC objects",
"occ0": {
"occHwmonPath": "/sys/bus/platform/drivers/occ-hwmon/occ-hwmon.1/hwmon/hwmon13",
"occRole": "MASTER",
"occState": "ACTIVE",
"pollResponse": [
"0000: 93000F00 030C0100 00000000 00000000",
"0010: 6F705F70 31315F32 35303432 38610000",
"0020: …
```
> bmcdump: Add occ-control data to plugin
